spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notebook
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    allow-circular-references: true

server:
  port: 8080

logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: error
        type:
          descriptor:
            sql:
              BasicBinder: error
              BasicExtractor: error
        engine:
          internal:
            StatisticalLoggingSessionEventListener: error
        loader:
          entity:
            plan: error
        orm:
          sql:
            ast:
              tree: error
