spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notebook
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR
              BasicExtractor: ERROR
        engine:
          internal:
            StatisticalLoggingSessionEventListener: ERROR
        loader:
          entity:
            plan: ERROR
        orm:
          sql:
            ast:
              tree: ERROR